### ISSUE TITLE
BRDF的公式貌似打错了?

### ISSUE THREAD

**Issue by but0n** [QianMo/PBR-White-Paper#1]
![image](https://user-images.githubusercontent.com/7625588/50385432-61037b00-0710-11e9-973a-ff918e6abeaf.png)

![image](https://user-images.githubusercontent.com/7625588/50385442-81333a00-0710-11e9-9616-6f39c55eb2f0.png)

**Comment by QianMo** [comment]
确实笔误了，我来改正。

**Comment by QianMo** [comment]
谢谢指出，已修正。

**Comment by QianMo** [comment]
谢谢指出，已修正。
